/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.tilab.msn;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class string {
        /**  APPLICATION SPECIFIC PARAMETERS 
         */
        public static final int app_name=0x7f030000;
        public static final int contacts_update_time=0x7f030003;
        /**  ERROR MESSAGES 
         */
        public static final int error_msg_jadegw_connection=0x7f03000a;
        /**  JADE PLATFORM CONNECTION PARAMETERS 
         */
        public static final int jade_platform_host=0x7f030008;
        public static final int jade_platform_port=0x7f030009;
        public static final int menuitem_exit=0x7f030007;
        public static final int menuitem_listview=0x7f030006;
        /**  MENU ITEM PARAMETERS 
         */
        public static final int menuitem_mapview=0x7f030005;
        public static final int msn_service_desc_name=0x7f030001;
        public static final int msn_service_desc_type=0x7f030002;
        /**  UI SPECIFIC PARAMETERS 
         */
        public static final int toast_duration=0x7f030004;
    }
}
