/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package it.telecomitalia.mock.gps;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int map=0x7f020000;
    }
    public static final class id {
        public static final int delay_edittext=0x7f050006;
        public static final int delay_textview=0x7f050005;
        public static final int empty_view_parent=0x7f050000;
        public static final int providername_textview=0x7f050002;
        public static final int start_service_btn=0x7f050007;
        public static final int stop_service_btn=0x7f050008;
        public static final int track_spinner=0x7f050004;
        public static final int tracks_textview=0x7f050003;
        public static final int welcome_textview=0x7f050001;
    }
    public static final class layout {
        public static final int empty=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int default_delay_ms=0x7f040002;
        public static final int default_tracks_dir=0x7f040001;
    }
}
